name: Publish Calculator App
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Build and Publish Project
        run: dotnet publish -c Release --self-contained -r win-x64 -p:PublishSingleFile=true
      # - name: Upload .exe as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Calculator.exe
      #     path: bin/Release/netcoreapp3.1/win-x64/publish/Calculator.exe
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/Release/netcoreapp3.1/win-x64/publish/Calculator.exe
          artifactContentType: application/exe
